#!/bin/bash

##
# Sends a Slack webhook containing a list
# of all the JIRA tickets since the last tag.
##

# Config
slack_webhook_url="$SLACK_WEBHOOK_URL"
tmp_filename="tmp-jira.txt"

# Get the number of commits since last tag
prev_tag=`git rev-list --tags --no-walk --max-count=1`
num_commits=`git rev-list $prev_tag..HEAD --count`

# Get a list of all the JIRA tickets since
git log --pretty=format:"%s" -n $num_commits \
    | grep -o [A-Z]+-[0-9]+ -E \
    | sort -t: -u -k1,1 \
    | while read -r t ; do echo -e "• $t (https://$JIRA_PREFIX.atlassian.net/browse/$t)" >> $tmp_filename ; done

# Send a Slack webhook
timestamp=`date +%s`
header="<!here> *Deploy Completed <!date^$timestamp^- {date_long_pretty} {time}|just now>*\n\n*JIRA Tickets Deployed:*"
payload=`< $tmp_filename sed "$!G" | paste -sd "\\n" -`
curl -X POST --data-urlencode "payload={\"text\": \"$SLACK_HEADER\n$payload\"}" $slack_webhook_url

# Cleanup, remove the temporary file
rm $tmp_filename
