#!/bin/bash

##
# Sends a Slack webhook containing a list of all
# the JIRA tickets since the last merge commit.
##

# Config
timestamp=`date +%s`
slack_webhook_url="$SLACK_WEBHOOK_URL"
tmp_filename="tmp-jira-tickets-$timestamp.txt"

# Get a list of all the JIRA tickets since last merge commit
git log --pretty=format:"%s" $(git log --merges -n 2 --oneline | tail -1 | cut -f1 -d' ')..HEAD \
    | grep -o [A-Z]+-[0-9]+ -E \
    | sort -t: -u -k1,1 \
    | while read -r t ; do echo -e "• $t (https://$JIRA_PREFIX.atlassian.net/browse/$t)" >> $tmp_filename ; done

if [ ! -f "$tmp_filename" ]; then
  echo 'No JIRA tickets detected since last merge commit.'
  exit 0
fi

# Send a Slack webhook
header="> <!here> *JIRA Tickets Mentioned <!date^$timestamp^- {date_long_pretty} {time}|just now>*\n"
payload=`< $tmp_filename sed '/^[ \t]*$/d' | paste -sd "\\n" -`
curl -X POST --data-urlencode "payload={\"text\": \"$header\n$payload\"}" $slack_webhook_url

# Cleanup, remove the temporary file
rm $tmp_filename
